"""Add Person model

Revision ID: 2d173ed1b990
Revises: 24d909906931
Create Date: 2026-07-23 15:03:07.839627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d173ed1b990'
down_revision: Union[str, Sequence[str], None] = '24d909906931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_persons_id'), 'persons', ['id'], unique=False)

    # --- INICIO DE LA MIGRACIÓN DE DATOS ---
    # Deshabilitar constraints temporalmente en owner_profiles (las FKs en teams apuntan aquí)
    op.execute("ALTER TABLE teams DROP CONSTRAINT IF EXISTS teams_owner_id_fkey")
    op.execute("ALTER TABLE owner_profiles DROP CONSTRAINT IF EXISTS owner_profiles_pkey CASCADE")
    
    # Desplazar los IDs de owner_profiles para evitar colisiones con pro_profiles (offset 10000)
    op.execute("UPDATE owner_profiles SET id = id + 10000")
    op.execute("UPDATE teams SET owner_id = owner_id + 10000")
    
    op.execute("ALTER TABLE owner_profiles ADD PRIMARY KEY (id)")
    op.execute("ALTER TABLE teams ADD CONSTRAINT teams_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES owner_profiles(id) ON DELETE RESTRICT")

    # Copiar datos a persons
    op.execute("INSERT INTO persons (id, user_id, full_name, photo_url, type) SELECT id, user_id, full_name, photo_url, 'pro_profile' FROM pro_profiles")
    op.execute("INSERT INTO persons (id, user_id, full_name, photo_url, type) SELECT id, user_id, full_name, photo_url, 'owner_profile' FROM owner_profiles")
    
    # Actualizar la secuencia de persons
    op.execute("SELECT setval(pg_get_serial_sequence('persons', 'id'), COALESCE((SELECT MAX(id) FROM persons), 1))")
    # --- FIN DE LA MIGRACIÓN DE DATOS ---

    op.drop_index(op.f('ix_owner_profiles_id'), table_name='owner_profiles')
    op.drop_constraint('owner_profiles_user_id_key', 'owner_profiles', type_='unique')
    op.drop_constraint('owner_profiles_user_id_fkey', 'owner_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'owner_profiles', 'persons', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('owner_profiles', 'full_name')
    op.drop_column('owner_profiles', 'user_id')
    op.drop_column('owner_profiles', 'photo_url')
    
    op.drop_index(op.f('ix_pro_profiles_id'), table_name='pro_profiles')
    op.drop_constraint('pro_profiles_user_id_key', 'pro_profiles', type_='unique')
    op.drop_constraint('pro_profiles_user_id_fkey', 'pro_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'pro_profiles', 'persons', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('pro_profiles', 'full_name')
    op.drop_column('pro_profiles', 'user_id')
    op.drop_column('pro_profiles', 'photo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pro_profiles', sa.Column('photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pro_profiles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('pro_profiles', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pro_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('pro_profiles_user_id_fkey'), 'pro_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('pro_profiles_user_id_key'), 'pro_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_pro_profiles_id'), 'pro_profiles', ['id'], unique=False)
    op.add_column('owner_profiles', sa.Column('photo_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('owner_profiles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('owner_profiles', sa.Column('full_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'owner_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('owner_profiles_user_id_fkey'), 'owner_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('owner_profiles_user_id_key'), 'owner_profiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_owner_profiles_id'), 'owner_profiles', ['id'], unique=False)
    op.drop_index(op.f('ix_persons_id'), table_name='persons')
    op.drop_table('persons')
    # ### end Alembic commands ###
