"""change age to birth_date

Revision ID: 7476b47c515d
Revises: ace23ad2c644
Create Date: 2026-07-22 13:46:10.766977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7476b47c515d'
down_revision: Union[str, Sequence[str], None] = 'ace23ad2c644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pro_profiles', sa.Column('birth_date', sa.Date(), nullable=True))
    op.execute("UPDATE pro_profiles SET birth_date = CURRENT_DATE - (age || ' years')::interval")
    op.alter_column('pro_profiles', 'birth_date', nullable=False)
    op.drop_column('pro_profiles', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pro_profiles', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.execute("UPDATE pro_profiles SET age = EXTRACT(YEAR FROM age(CURRENT_DATE, birth_date))")
    op.alter_column('pro_profiles', 'age', nullable=False)
    op.drop_column('pro_profiles', 'birth_date')
    # ### end Alembic commands ###
