"""add contract is_deleted

Revision ID: 8f0c5ba35ebc
Revises: 76efd9a99923
Create Date: 2026-07-27 18:26:14.707739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0c5ba35ebc'
down_revision: Union[str, Sequence[str], None] = '76efd9a99923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'is_deleted')
    # ### end Alembic commands ###
