"""Add transfer_offer_id to contract

Revision ID: ace23ad2c644
Revises: 8654e1047ef1
Create Date: 2026-07-22 13:36:04.316377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace23ad2c644'
down_revision: Union[str, Sequence[str], None] = '8654e1047ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('transfer_offer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'transfer_offers', ['transfer_offer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'transfer_offer_id')
    # ### end Alembic commands ###
