"""add_coach_analyst_roles

Revision ID: b6aa4d6a0fd9
Revises: baccf3bc3fe8
Create Date: 2026-07-26 16:55:04.244494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6aa4d6a0fd9'
down_revision: Union[str, Sequence[str], None] = 'baccf3bc3fe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE cs2role_enum ADD VALUE IF NOT EXISTS 'Coach'")
    op.execute("ALTER TYPE cs2role_enum ADD VALUE IF NOT EXISTS 'Analyst'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
