"""add proposed contract fields nullable

Revision ID: baccf3bc3fe8
Revises: 2d173ed1b990
Create Date: 2026-07-26 16:06:15.486539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baccf3bc3fe8'
down_revision: Union[str, Sequence[str], None] = '2d173ed1b990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer_offers', sa.Column('proposed_salary', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('transfer_offers', sa.Column('proposed_duration_months', sa.Integer(), nullable=True))
    op.add_column('transfer_offers', sa.Column('proposed_buyout_clause', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer_offers', 'proposed_buyout_clause')
    op.drop_column('transfer_offers', 'proposed_duration_months')
    op.drop_column('transfer_offers', 'proposed_salary')
    # ### end Alembic commands ###
