"""Add duration and buyout_clause

Revision ID: d7c52078efb7
Revises: 8b6e9212a1ed
Create Date: 2026-07-13 23:05:35.865026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c52078efb7'
down_revision: Union[str, Sequence[str], None] = '8b6e9212a1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('duration_months', sa.Integer(), nullable=False))
    op.add_column('contracts', sa.Column('buyout_clause', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'buyout_clause')
    op.drop_column('contracts', 'duration_months')
    # ### end Alembic commands ###
