"""add_is_renegotiation

Revision ID: e643c50a9b1f
Revises: b6aa4d6a0fd9
Create Date: 2026-07-26 17:32:47.323038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e643c50a9b1f'
down_revision: Union[str, Sequence[str], None] = 'b6aa4d6a0fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('is_renegotiation', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'is_renegotiation')
    # ### end Alembic commands ###
